spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/time-deal
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
